# Generated by Django 5.2.15 on 2026-06-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='selfie',
            field=models.ImageField(upload_to='attendance/'),
        ),
    ]
