# Generated by Django 5.2.15 on 2026-06-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_selfie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_longitude',
        ),
    ]
