# Generated by Django 5.2.15 on 2026-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkout_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_checkout/'),
        ),
    ]
